/*import bcrypt from 'bcryptjs';
const data = {
    users:[
      {
        name: 'Efe',
        email:'efefbi@yahoo.com',
        password: bcrypt.hashSync('gabone911', 8),
        isAdmin: true,
    },
    {
      name: 'John',
      email:'johnfbi@yahoo.com',
      password: bcrypt.hashSync('gabone911', 8),
      isAdmin: false,
  }
  ],
    products:[
    {
    //_id:'1',
    name:'Lion frame',
    category: 'Frame',
    image: './images/p1.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Vigo',
    rating: 4.5,
    numReviews: 10,
    description: 'High quality product',
   },
   {
    //_id:'2',
    name:'Nike T-Shirt',
    category: 'Shirt',
    image: './images/p2.jpg',
    price: 100,
    countInStock: 20,
    brand: 'Nike',
    rating: 5.0,
    numReviews: 15,
    description: 'High quality product',
   },
   {
    //_id:'3',
    name:'Nike Trainers',
    category: 'Footwear',
    image: './images/p3.jpg',
    price: 60,
    countInStock: 0,
    brand: 'Nike',
    rating: 4.0,
    numReviews: 12,
    description: 'High quality product',
   },
   {
    //_id:'4',
    name:'addidas shirt',
    category: 'Shirt',
    image: './images/p4.jpg',
    price: 50,
    countInStock: 15,
    brand: 'Addidas',
    rating: 4.5,
    numReviews: 20,
    description: 'High quality product',
   },
   {
    //_id:'5',
    name:'Rolex Watch',
    category: 'Watches',
    image: './images/p5.jpg',
    price: 1200,
    countInStock: 5,
    brand: 'Rolex',
    rating: 5.0,
    numReviews: 100,
    description: 'High quality product',
   },
   {
    //_id:'6',
    name:'Channel Hat',
    category: 'Hat',
    image: './images/p6.jpg',
    price: 800,
    countInStock: 30,
    brand: 'Channel',
    rating: 5.0,
    numReviews: 40,
    description: 'High quality product',
   },
 ]
};
export default data;
*/
import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;