const data = {
    products:[
    {
    _id:'1',
    name:'Lion frame',
    category: 'Frame',
    image: './images/p1.jpg',
    price: 120,
    brand: 'Vigo',
    rating: 4.5,
    numReviews: 10,
    description: 'High quality product',
   },
   {
    _id:'2',
    name:'Nike T-Shirt',
    category: 'Shirt',
    image: './images/p2.jpg',
    price: 100,
    brand: 'Nike',
    rating: 5.0,
    numReviews: 15,
    description: 'High quality product',
   },
   {
    _id:'3',
    name:'Nike Trainers',
    category: 'Footwear',
    image: './images/p3.jpg',
    price: 60,
    brand: 'Nike',
    rating: 4.0,
    numReviews: 12,
    description: 'High quality product',
   },
   {
    _id:'4',
    name:'addidas shirt',
    category: 'Shirt',
    image: './images/p4.jpg',
    price: 50,
    brand: 'Addidas',
    rating: 4.5,
    numReviews: 20,
    description: 'High quality product',
   },
   {
    _id:'5',
    name:'Rolex Watch',
    category: 'Watches',
    image: './images/p5.jpg',
    price: 1200,
    brand: 'Rolex',
    rating: 5.0,
    numReviews: 100,
    description: 'High quality product',
   },
   {
    _id:'6',
    name:'Channel Hat',
    category: 'Hat',
    image: './images/p6.jpg',
    price: 800,
    brand: 'Channel',
    rating: 5.0,
    numReviews: 40,
    description: 'High quality product',
   },
 ]
};
export default data;